name: cognac
channels:
- defaults
- conda-forge
dependencies:
- asn1crypto=0.22.0
- backports=1.0
- backports.functools_lru_cache=1.4
- backports.shutil_get_terminal_size=1.0.0
- backports_abc=0.5
- bleach=2.0.0
- bokeh=0.12.9
- bottleneck=1.2.1
- ca-certificates=2017.7.27.1
- cairo=1.14.6
- cartopy=0.15.1
- certifi=2017.7.27.1
- cffi=1.10.0
- chardet=3.0.4
- click=6.7
- cloudpickle=0.4.0
- configparser=3.5.0
- cryptography=2.0.3
- curl=7.54.1
- cycler=0.10.0
- cyordereddict=1.0.0
- dask=0.15.4
- dask-core=0.15.4
- dbus=1.10.22
- decorator=4.1.2
- distributed=1.19.2
- entrypoints=0.2.3
- enum34=1.1.6
- expat=2.2.1
- fontconfig=2.12.1
- freetype=2.7
- functools32=3.2.3.2
- futures=3.0.5
- geos=3.5.1
- gettext=0.19.7
- glib=2.51.4
- gmp=6.1.2
- graphite2=1.3.9
- graphviz=2.38.0
- gst-plugins-base=1.8.0
- gstreamer=1.8.0
- h5netcdf=0.4.3
- h5py=2.7.1
- harfbuzz=1.4.3
- hdf4=4.2.12
- hdf5=1.8.18
- heapdict=1.0.0
- html5lib=0.999999999
- icu=58.1
- idna=2.6
- ipaddress=1.0.18
- ipykernel=4.6.1
- ipython=5.5.0
- ipython_genutils=0.2.0
- ipywidgets=7.0.1
- jinja2=2.9.6
- jpeg=9b
- jsonschema=2.6.0
- jupyter=1.0.0
- jupyter_client=5.1.0
- jupyter_console=5.1.0
- jupyter_core=4.3.0
- krb5=1.14.2
- libffi=3.2.1
- libiconv=1.14
- libnetcdf=4.4.1.1
- libpng=1.6.28
- libsodium=1.0.10
- libssh2=1.8.0
- libtiff=4.0.7
- libtool=2.4.6
- libxcb=1.12
- libxml2=2.9.5
- libxslt=1.1.29
- locket=0.2.0
- lxml=4.0.0
- markupsafe=1.0
- matplotlib=2.1.0
- mistune=0.7.4
- msgpack-python=0.4.8
- nbconvert=5.3.1
- nbformat=4.4.0
- ncurses=5.9
- netcdf4=1.3.0
- notebook=5.1.0
- olefile=0.44
- openssl=1.0.2l
- owslib=0.15.0
- pandas=0.20.3
- pandoc=1.19.2
- pandocfilters=1.4.1
- pango=1.40.4
- partd=0.3.8
- pathlib2=2.3.0
- pcre=8.39
- pexpect=4.2.1
- pickleshare=0.7.4
- pillow=4.3.0
- pip=9.0.1
- pixman=0.34.0
- proj4=4.9.3
- prompt_toolkit=1.0.15
- psutil=5.3.1
- ptyprocess=0.5.2
- pycparser=2.18
- pyepsg=0.3.2
- pygments=2.2.0
- pyopenssl=17.2.0
- pyparsing=2.2.0
- pyproj=1.9.5.1
- pyqt=5.6.0
- pyshp=1.2.12
- pysocks=1.6.7
- python=2.7.14
- python-dateutil=2.6.1
- pytz=2017.2
- pyyaml=3.12
- pyzmq=16.0.2
- qt=5.6.2
- qtconsole=4.3.1
- readline=6.2
- requests=2.18.4
- scandir=1.6
- setuptools=36.3.0
- shapely=1.6.1
- simplegeneric=0.8.1
- singledispatch=3.4.0.3
- sip=4.18
- six=1.11.0
- sortedcontainers=1.5.7
- sqlite=3.13.0
- ssl_match_hostname=3.5.0.1
- subprocess32=3.2.7
- tblib=1.3.2
- terminado=0.6
- testpath=0.3.1
- tk=8.5.19
- toolz=0.8.2
- tornado=4.5.2
- traitlets=4.3.2
- urllib3=1.22
- wcwidth=0.1.7
- webencodings=0.5
- wheel=0.30.0
- widgetsnbextension=3.0.3
- xarray=0.9.6
- xorg-libxau=1.0.8
- xorg-libxdmcp=1.1.2
- xz=5.2.3
- yaml=0.1.6
- zeromq=4.2.1
- zict=0.1.3
- zlib=1.2.8
- libgfortran=3.0.0
- libgfortran-ng=7.2.0
- libstdcxx-ng=7.2.0
- mkl=2018.0.0
- numpy=1.13.3
- scipy=0.19.1
- pip:
  - backports-abc==0.5
  - backports.functools-lru-cache==1.4
  - backports.shutil-get-terminal-size==1.0.0
  - backports.ssl-match-hostname==3.5.0.1
  - gsw==3.0.6
  - ipython-genutils==0.2.0
  - jupyter-client==5.1.0
  - jupyter-console==5.1.0
  - jupyter-core==4.3.0
  - prompt-toolkit==1.0.15
