name: cognac
channels:
- conda-forge
- defaults
dependencies:
- cartopy=0.15.1
- click=6.7
- dask=0.15.4
- dask-core=0.15.4
- graphviz=2.38.0
- h5netcdf=0.4.3
- h5py=2.7.1
- hdf4=4.2.12
- hdf5=1.8.18
- libnetcdf=4.4.1.1
- matplotlib=2.1.0
- netcdf4=1.3.0
- pandas=0.20.3
- xarray=0.9.6
- numpy=1.13.3
- scipy=0.19.1
- pip:
  - gsw==3.0.6
