name: cognac
channels:
  - conda-forge
dependencies:
  - gsw
  - netcdf4
  - xarray
  - cartopy
  - hvplot
  - graphviz
  - python
  - jupyterlab
  - panel
  - holoviews
  - bokeh
  - geoviews
  - nodejs
  - datashader
  - python-graphviz

