name: cognac
channels:
  - defaults
dependencies:
  - gsw
  - netcdf4
  - xarray
  - cartopy
  - hvplot
  - dask-jobqueue
  - graphviz
  - python
  - jupyterlab
  - ffmpeg
  - panel
  - holoviews
  - bokeh
  - geoviews
  - nodejs
  - datashader
  - distributed
  - python-graphviz

