name: cognac
channels:
  - conda-forge
dependencies:
  - pangeo-notebook==2020.07.03
  - xarray
  - hvplot
  - geoviews
  - datashader
  - nodejs
  - cartopy
  - gsw
  - pip
  - pip:
    - pynmea2
    - graphviz
    - -e ../